version: '3.8'

services:
  market-analysis:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 4002:4002
    volumes:
      - ..:/workspace:cached
    environment:
        BACKEND_DBCONN: mongodb://db:27017
        BACKEND_DEBUG: true
        BACKEND_PORT: 4002
    command: sleep infinity

  db:
    image: mongo:latest
    restart: unless-stopped
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    volumes:
      - db-data:/var/lib/mongodb/data
      - ../.devcontainer/mongo:/etc/mongo/

volumes:
  db-data: