version: '3.8'

services:
  market-analysis:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 4002:4002
    volumes:
      - ..:/workspace:cached
    environment:
        BACKEND_DBCONN: mongodb://db:27017
        BACKEND_DBUSER: root
        BACKEND_DBPASS: AdLjmUkCqRBzyJ2
        BACKEND_DEBUG: true
        BACKEND_PORT: 4002
    command: sleep infinity

  db:
    image: mongo:latest
    environment:
    # provide your credentials here
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=AdLjmUkCqRBzyJ2
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mongodb/data

volumes:
  db-data: